apiVersion: v1
kind: Service
metadata:
  name: {{ template "users.fullname" . }}
  labels:
    app: {{ template "users.name" . }}
    chart: {{ template "users.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.metrics.prometheus.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ default .Values.service.port .Values.metrics.prometheus.port | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ template "users.name" . }}
  selector:
    app: {{ template "users.name" . }}
    release: {{ .Release.Name }}
